# ===================================
#  Relation Behavior Config
# ===================================

product_attributes:
    label: Attribute
    list: ~/plugins/octommerce/octommerce/models/productattribute/columns_relation_product.yaml
    deferredBinding: true
    view:
        toolbarButtons: add|remove
        showCheckboxes: true
    pivot:
        form: $/octommerce/octommerce/models/productattribute/fields_relation_product.yaml

variations:
    label: Variation
    list: ~/plugins/octommerce/octommerce/models/product/columns_relation_product.yaml
    form: ~/plugins/octommerce/octommerce/models/product/fields_relation_product.yaml
    view:
        toolbarButtons: create|delete|add|remove
        showCheckboxes: true

up_sells:
    label: Up Sell
    list: ~/plugins/octommerce/octommerce/models/product/columns_relation_product.yaml
    view:
        toolbarButtons: link|unlink
        showCheckboxes: true

cross_sells:
    label: Cross Sell
    list: ~/plugins/octommerce/octommerce/models/product/columns_relation_product.yaml
    view:
        toolbarButtons: link|unlink
        showCheckboxes: true

product_variations:
    label: Product Variations
    list: ~/plugins/octommerce/octommerce/models/variation/columns.yaml
    form: ~/plugins/octommerce/octommerce/models/variation/fields.yaml
    view:
        toolbarButtons: create|delete
        showCheckboxes: true